name: 'egypt_tech_jobs'
version: '1.0.0'
config-version: 2

profile: 'egypt_tech_jobs'

model-paths: ["models"]
macro-paths: ["macros"]

models:
  egypt_tech_jobs:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table